import { Metadata } from "next";
/* This is metadata generated by ChatGPT, it could not be real */


export const TemplateMetadata = {
  title: "Egg Cracker",
  description: "A clicker game to break your eggs",
  applicationName: "Egg Cracker",
  authors: [
    {
      name: "Freddy Javier Saez Avila",
      url: "https://freddyjs.es",
    },
  ],
  keywords: ["Egg", "Egg Cracker", "Game", "Clicker"],
  creator: "Freddy Javier Saez Avila",
  publisher: "Egg Cracker Studios",
  generator: "Next.js",

  // Open Graph configuration for better social media sharing
  openGraph: {
    title: "Egg Cracker - Break your eggs, win surprises!",
    description: "A fun clicker game where you crack eggs and discover hidden surprises!",
    url: "https://eggcrackergame.com",
    siteName: "Egg Cracker", 
    images: [
      {
        url: "https://eggcrackergame.com/og-image.png", // Image for social media preview
        width: 1200,
        height: 630,
        alt: "Egg Cracker - Crack eggs and win!",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  // Twitter card configuration for sharing on Twitter
  twitter: {
    card: "summary_large_image",
    title: "Egg Cracker - Break your eggs, win surprises!",
    description: "A fun clicker game where you crack eggs and discover hidden surprises!",
    creator: "@freddyjs", // Replace with your Twitter handle if you have one
    images: ["https://eggcrackergame.com/twitter-image.png"],
  },

  // Icons for the web application
  icons: {
    icon: "/favicon.ico",            // Main favicon
    shortcut: "/favicon-16x16.png",  // Smaller favicon
    apple: "/apple-touch-icon.png",  // Icon for Apple devices
  },

 

  // Additional metadata for SEO and categorization
  category: "games", // Category for the app
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
    },
  },

  // Language and alternate URL configurations
  alternates: {
    canonical: "https://eggcrackergame.com",
    languages: {
      en: "https://eggcrackergame.com/en",
      es: "https://eggcrackergame.com/es",
    },
  },
} as Metadata;


export default TemplateMetadata